name: Security Audit

on:
  schedule:
    - cron: '0 3 * * 1' # Every Monday 3AM UTC
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Run Audit
      run: npm audit --audit-level=moderate


